version: '3.8'

services:
  typesense:
    image: typesense/typesense:0.25.1
    container_name: neetlogiq-typesense
    ports:
      - "8108:8108"
    environment:
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_API_KEY=xyz
      - TYPESENSE_ENABLE_CORS=true
    volumes:
      - typesense-data:/data
    command: '--data-dir /data --api-key=xyz --listen-port 8108 --enable-cors'
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8108/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  typesense-data:
    driver: local
