name = "neetlogiq-backend"
main = "src/index.js"
compatibility_date = "2024-01-15"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "neetlogiq-db"
database_id = "fd98253c-ecfb-4ec6-a221-45ddfd5edde0"

# Environment variables
[vars]
ENVIRONMENT = "production"

# CORS configuration
[env.production.vars]
ENVIRONMENT = "production"
