name = "neetlogiq-backend"
main = "src/index.js"
compatibility_date = "2024-01-15"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "neetlogiq-db"
database_id = "769bb466-8366-4584-bd51-b78bb60d5e6c"

# Environment variables
[vars]
ENVIRONMENT = "production"

# CORS configuration
[env.production.vars]
ENVIRONMENT = "production"
