name = "neetlogiq-backend"
main = "src/index.js"
compatibility_date = "2024-01-15"

# D1 Database configuration
[[d1_databases]]
binding = "DB"
database_name = "neetlogiq-db"
database_id = "769bb466-8366-4584-bd51-b78bb60d5e6c"

# AI Model binding
[ai]
binding = "AI"

# Vectorize database for AI embeddings
[[vectorize]]
binding = "VECTORIZE_INDEX"
index_name = "neetlogiq-index"

# Environment variables
[vars]
ENVIRONMENT = "development"
INDEXER_AUTH_SECRET = "dev-secret-key-change-in-production"